metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prom-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/anwarfaisal320/argo-infra.git
    path: helm-charts/kube-prometheus-stack
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Force=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
